### ISSUE TITLE
some of links poster in Gitter by HangoutNotifier are not well formated

### ISSUE THREAD

**Issue by diraulo** [AgileVentures/agile-bot#19]
posting this
![](https://www.dropbox.com/s/o3ve02x3c9egict/Screenshot%202016-06-10%2010.26.40.png?dl=1)

instead of something like this
![](https://www.dropbox.com/s/56otj8f4ctqf67y/Screenshot%202016-06-10%2010.30.37.png?dl=1)

**Comment by tansaku** [comment]
you're saying it's too verbose?

**Comment by diraulo** [comment]
The link is broken

**Comment by diraulo** [comment]
I think there should be an `_` between the 2 `/` -- it's lost somehow resulting in posting a broken link

**Comment by tansaku** [comment]
ah - we'll need to investigate that - thanks for spotting it

**Comment by tansaku** [comment]
It's weird - I wonder if gitter formatting suddenly changed ...

**Comment by tansaku** [comment]
looks like it's gone back to normal now

**Comment by tansaku** [comment]
I didn't see the issue again over the weekend ... would be nice to format the links so they aren't unfurled with the hash - e.g. [click to join hangout]()

**Comment by tansaku** [comment]
does not seem to have recurred - close for now
